### ISSUE TITLE
Problème d'erreurs sur le Site Web

### ISSUE THREAD

**Issue by Ripus28** [Rolisteam/rolisteam#96]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 
Operating System and version (remove irrelevant): 
*  Windows (XP,Vista,7,8,10..)

Rolisteam Setting (remove irrelevant):  
* GM and Server

**Problème Concernant le site Web**

Bonjour,

j'ai remarqué un bug dans l'inscription du forum :

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "derky.sortablescaptcha.captcha.sortables".' in /home/www/rolisteam/forum/vendor/symfony/dependency-injection/ContainerBuilder.php:805 Stack trace: #0 /home/www/rolisteam/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(451): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('derky.sortables...') #1 /home/www/rolisteam/forum/phpbb/captcha/factory.php(48): Symfony\Component\DependencyInjection\ContainerBuilder->get('derky.sortables...') #2 /home/www/rolisteam/forum/includes/ucp/ucp_register.php(242): phpbb\captcha\factory->get_instance('derky.sortables...') #3 /home/www/rolisteam/forum/includes/functions_module.php(676): ucp_register->main('register', NULL) #4 /home/www/rolisteam/forum/includes/functions_module.php(998): p_master->load_active(false) #5 /home/www/rolisteam/forum/ucp.php(70): p_master->load('ucp', 'register') #6 {m in /home/www/rolisteam/forum/vendor/symfony/dependency-injection/ContainerBuilder.php on line 805

Du coup impossible de s’inscrire, également sur le nouveau site, les menus du côté droit ne fonctionne pas à tous les coups ainsi que le formulaire de contact. (The requested URL /fr/php/submit.php was not found on this server)

Je me suis inscrit sur la chaîne Youtube, alors j’espère que vous êtes toujours active, par avance, je vous envoie tous mes remercient pour votre fantastique travail.

Dans l'attente de vous lire.

**Comment by obiwankennedy** [comment]
ok, je vais verrifier cela.

**Comment by obiwankennedy** [comment]
Ok cela devrait être mieux. 
Le formulaire remarche (au moins depuis la version anglaise) et le forum a bien son extension pour le spam. Il est possible de créer un compte, (du moins on passe l'écran avec le gros messages d'erreurs).
